In [1]:
import os

import numpy as np
import matplotlib.pyplot as plt

import librosa
import librosa.display
import IPython.display

import tensorflow as tf

In [2]:


data_path = './data4/'

nb_classes = len(os.listdir(data_path))

print("nb_class: ", nb_classes)

for sub_path in range(nb_classes):
    item_num = os.listdir(data_path+str(sub_path+1))
    print("item_num in class", sub_path+1, ": " , len(item_num))

nb_class:  5
item_num in class 1 :  3
item_num in class 2 :  2
item_num in class 3 :  1
item_num in class 4 :  2
item_num in class 5 :  2


In [3]:

y = [None] * nb_classes
sr = [None] * nb_classes

for sub_path in range(nb_classes):
    item_num = os.listdir(data_path+str(sub_path+1))
    
    y[sub_path] = [None] * len(item_num)
    sr[sub_path] = [None] * len(item_num)

    
    for i in range(len(item_num)):
        y[sub_path][i], sr[sub_path][i] = librosa.load(data_path + str(sub_path+1) + '/' + str(i) + '.wav')
        print("load", i,"in", sub_path+1, "done!")

load 0 in 1 done!
load 1 in 1 done!
load 2 in 1 done!
load 0 in 2 done!
load 1 in 2 done!
load 0 in 3 done!
load 0 in 4 done!
load 1 in 4 done!
load 0 in 5 done!
load 1 in 5 done!


In [5]:
# audio data verification

for sub_path in range(nb_classes):
    item_num = os.listdir(data_path+str(sub_path+1))
    
    for i in range(len(item_num)):
        print("Shape", i,"in", sub_path+1, ":", y[sub_path][i].shape)

Shape 0 in 1 : (15736544,)
Shape 1 in 1 : (19245216,)
Shape 2 in 1 : (19707744,)
Shape 0 in 2 : (8401504,)
Shape 1 in 2 : (44215840,)
Shape 0 in 3 : (37069728,)
Shape 0 in 4 : (23162784,)
Shape 1 in 4 : (43805344,)
Shape 0 in 5 : (10233824,)
Shape 1 in 5 : (38102304,)


In [6]:
# sampling rate verification

print(sr)
print(sr[0][0])

[[22050, 22050, 22050], [22050, 22050], [22050], [22050, 22050], [22050, 22050]]
22050


In [7]:
# audio data verification

for sub_path in range(nb_classes):
    item_num = os.listdir(data_path+str(sub_path+1))
    
    for i in range(len(item_num)):
        print("Shape", i,"in", sub_path+1, ":", y[sub_path][i].shape)
        
        


Shape 0 in 1 : (15736544,)
Shape 1 in 1 : (19245216,)
Shape 2 in 1 : (19707744,)
Shape 0 in 2 : (8401504,)
Shape 1 in 2 : (44215840,)
Shape 0 in 3 : (37069728,)
Shape 0 in 4 : (23162784,)
Shape 1 in 4 : (43805344,)
Shape 0 in 5 : (10233824,)
Shape 1 in 5 : (38102304,)


In [11]:
# audio_data_stack


audio_data = [None] * nb_classes

for sub_path in range (0, nb_classes):
    item_num = os.listdir(data_path+str(sub_path+1))
    
    for i in range(len(item_num)):
        
        if len(item_num) == 1:
            audio_data[sub_path] = y[sub_path][0] 

        else:

            if i == 0:
                audio_data[sub_path] = np.hstack([y[sub_path][i], y[sub_path][i+1]]) 

            elif i == 1:
                continue

            else:
                audio_data[sub_path] = np.hstack([audio_data[sub_path], y[sub_path][i]]) 

print("\nStacked Audio raw data")    
for sub_path in range (0, nb_classes):        
    print(audio_data[sub_path].shape)            


Stacked Audio raw data
(54689504,)
(52617344,)
(37069728,)
(66968128,)
(48336128,)


In [12]:
print("\nStacked Audio raw data")    
for sub_path in range (0, nb_classes):        
    print(audio_data[sub_path].shape)

min = 9999999999

for i in range (0, 5):
    if min > audio_data[i].shape[0]:
        min = audio_data[i].shape[0] 

print(min)

input_data_size = 460

min = int(min/6)

print(min)


min = min - min %(input_data_size * input_data_size)
    

print("\nResized Audio raw data")    
for i in range (0, 5):
    audio_data[i] = audio_data[i][0:min]
    print(audio_data[i].shape)


#print("\nReshaped Audio raw data")    
#for i in range (0, 5):
#    audio_data[i] = audio_data[i].reshape(-1, 1)
#    print(audio_data[i].shape)      
    
print("\nReshaped Audio raw data")    
for i in range (0, 5):
    audio_data[i] = audio_data[i].reshape(-1, input_data_size * input_data_size)
    print(audio_data[i].shape)  



Stacked Audio raw data
(54689504,)
(52617344,)
(37069728,)
(66968128,)
(48336128,)
37069728
6178288

Resized Audio raw data
(6136400,)
(6136400,)
(6136400,)
(6136400,)
(6136400,)

Reshaped Audio raw data
(29, 211600)
(29, 211600)
(29, 211600)
(29, 211600)
(29, 211600)


In [13]:
# labeling
y = [None] * nb_classes

    
for i in range (0, nb_classes):
    y[i] = np.ones((int(min/(input_data_size * input_data_size)), 1), dtype='int') * (i+1) -1
    print(y[i].shape)


for i in range (0, nb_classes):
    audio_data[i] = np.hstack([audio_data[i], y[i]])
    print(audio_data[i].shape)

    

(29, 1)
(29, 1)
(29, 1)
(29, 1)
(29, 1)
(29, 211601)
(29, 211601)
(29, 211601)
(29, 211601)
(29, 211601)


In [14]:
# input data shuffling


audio_data_append = []

for i in range (0, nb_classes):
    
    if i == 0:
        audio_data_append = np.vstack([audio_data[i], audio_data[i+1]])
    
    elif i == 1:
        continue
        
    else:
        audio_data_append = np.vstack([audio_data_append, audio_data[i]])


print(audio_data_append.shape)

print(audio_data_append[20])


np.random.shuffle(audio_data_append)

audio_data_shuffle = audio_data_append
print(audio_data_append.shape)

(145, 211601)
[-0.0076983  -0.02352953 -0.02818573 ...  0.0056458   0.01052093
  0.        ]
(145, 211601)


In [15]:
# labeled value one-hot encoding

audio_data_shuffle_T = audio_data_shuffle.transpose()

x_data_t = audio_data_shuffle_T[:-1]
y_data_t = audio_data_shuffle_T[-1:]
x_data = x_data_t.transpose()
y_data_t = y_data_t.flatten()



y_data_one_hot = tf.one_hot(y_data_t, nb_classes, dtype=tf.float32)

tf.InteractiveSession().as_default()
tf.tables_initializer().run()

y_data_one_hot = y_data_one_hot.eval()


print("FINAL IN/OUTPUT SHAPE")
print("Input X: ", x_data.shape)
print("Output Y_one_hot: ", y_data_one_hot.shape)

print("\nFINAL IN/OUTPUT DATA")
print(x_data)
print(y_data_one_hot)

FINAL IN/OUTPUT SHAPE
Input X:  (145, 211600)
Output Y_one_hot:  (145, 5)

FINAL IN/OUTPUT DATA
[[ 0.03953372  0.05508901  0.05231933 ...  0.04687595  0.05402173
   0.05538728]
 [-0.00401856 -0.00358174 -0.00222191 ... -0.02728347 -0.03176821
  -0.03719559]
 [-0.14958137 -0.18193342 -0.16024043 ... -0.29296631 -0.21872884
  -0.18979269]
 ...
 [-0.50348908 -0.5323875  -0.56361306 ... -0.21638727 -0.23412044
  -0.26359209]
 [-0.04003545  0.07358342  0.00224287 ... -0.04092641 -0.04462469
  -0.04518472]
 [ 0.00128514  0.00153497  0.00129209 ... -0.18931681 -0.20304005
  -0.17296927]]
[[0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.

In [16]:
# CNN (3 Conv + MP) + 1 FCN + 1 Output

training_number = 9000
learning_rate = 0.01

keep_prob = tf.placeholder(tf.float32)


with tf.variable_scope("sound_classifications-7-3") as scope:
    tf.variable_scope(scope, reuse=True)
    
    # Input Audio data of shape 460 * 460 = 211,600
    X = tf.placeholder(tf.float32, [None, 211600])
    X_reshaped = tf.reshape(X, [-1, 460, 460, 1])
    # 0 - 9 digits recognition = 10 classes
    Y = tf.placeholder(tf.float32, [None, nb_classes])


    # Conv 1
    W1 = tf.Variable(tf.random_normal([100, 100, 1, 32], stddev=0.01))
    L1 = tf.nn.conv2d(X_reshaped, W1, strides=[1, 1, 1, 1], padding='SAME')
    L1 = tf.nn.relu(L1)
    L1 = tf.nn.max_pool(L1, ksize=[1, 2, 2, 1],
                    strides=[1, 2, 2, 1], padding='SAME')
    L1 = tf.nn.dropout(L1, keep_prob=keep_prob)
    
    # X ImgIn shape=(?, 460, 460, 1)
    #    Conv      ->(?, 460, 460, 32)
    #    Pool      ->(?, 230, 230, 32)
    
    
    # Conv 2
    W2 = tf.Variable(tf.random_normal([100, 100, 32, 64], stddev=0.01))
    L2 = tf.nn.conv2d(L1, W2, strides=[1, 1, 1, 1], padding='SAME')
    L2 = tf.nn.relu(L2)
    L2 = tf.nn.max_pool(L2, ksize=[1, 2, 2, 1],
                    strides=[1, 2, 2, 1], padding='SAME')
    L2 = tf.nn.dropout(L2, keep_prob=keep_prob)
    
    # L1 ImgIn shape=(?, 230, 230, 32)
    #    Conv      ->(?, 230, 230, 64)
    #    Pool      ->(?, 115, 115, 64)
    
    
    # Conv 3
    W3 = tf.Variable(tf.random_normal([50, 50, 64, 128], stddev=0.01))
    L3 = tf.nn.conv2d(L2, W3, strides=[1, 1, 1, 1], padding='SAME')
    L3 = tf.nn.relu(L3)
    L3 = tf.nn.max_pool(L3, ksize=[1, 2, 2, 1],
                    strides=[1, 2, 2, 1], padding='SAME')
    L3 = tf.nn.dropout(L3, keep_prob=keep_prob)
    L3_flat = tf.reshape(L3, [-1, 128 * 58 * 58])
    
    # L2 ImgIn shape=(?, 115, 115, 64)
    #    Conv      ->(?, 115, 115, 128)
    #    Pool      ->(?, 58, 58, 128) 
    
    # FC
    W4 = tf.get_variable("W4", shape=[128 * 58 * 58, 625], initializer=tf.contrib.layers.xavier_initializer())
    b4 = tf.Variable(tf.random_normal([625]))
    L4 = tf.nn.relu(tf.matmul(L3_flat, W4) + b4)
    L4 = tf.nn.dropout(L4, keep_prob=keep_prob)
    
    # Output
    W5 = tf.get_variable("W5", shape=[625, nb_classes], initializer=tf.contrib.layers.xavier_initializer())
    b5 = tf.Variable(tf.random_normal([nb_classes]))
    logits = tf.matmul(L4, W5) + b5

print(tf.shape(L1))
print(tf.shape(logits))

Tensor("Shape:0", shape=(4,), dtype=int32)
Tensor("Shape_1:0", shape=(2,), dtype=int32)


In [17]:
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=Y))
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)


# Accuracy
is_correct = tf.equal(tf.arg_max(logits, 1), tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.

Instructions for updating:
Use `argmax` instead


In [ ]:
# Launch graph

batch_size = 200

cost_history = []
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for epoch in range(int(training_number/batch_size)):
        batch_count = int(x_data.shape[0]/batch_size)
        
        curr_cost = 0
        
        for i in range(batch_count):
    
            batch_xs, batch_ys = x_data[i* batch_size: i*batch_size+batch_size], y_data_one_hot[i*batch_size:i*batch_size+batch_size]
        
            sess.run(optimizer, feed_dict={X: batch_xs, Y: batch_ys, keep_prob: 0.7})

            curr_cost = sess.run(cost, feed_dict={X: batch_xs, Y: batch_ys, keep_prob: 0.7})
            
            
        if epoch % 10 == 0:    
            print(epoch, curr_cost)
            cost_history.append(curr_cost)
                                
                                
    print("Accuracy: ", accuracy.eval(session=sess, feed_dict={X: x_data, Y: y_data_one_hot, keep_prob: 1})) 

0 0
10 0
20 0
30 0
40 0


In [ ]:
plt.plot(cost_history)
plt.show()